addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    - jacoco.exec
    target_paths: 2a4cef31-05e1-4611-b300-ffed35b2fe0b
after_script:
- adb logcat -t 500
- for i in android-sample-ui-tests/target/screenshots/*; do echo $i; asciiview $i;
  done
after_success:
- ' wget --content-disposition http://search.maven.org/remotecontent?filepath=org/jacoco/jacoco/0.7.7.201606060606/jacoco-0.7.7.201606060606.zip '
- ' unzip -o jacoco-0.7.7.201606060606.zip  '
- ' cd lib  '
- ' mv * ../  '
- ' cd ..  '
- ' chmod a+x *  '
- ' cd $PWD  '
- ' rm  ''jacoco.exec'''
- ' export JAVA_TOOL_OPTIONS=-javaagent:$PWD/jacocoagent.jar=destfile=$PWD/jacoco.exec,append=true  '
- ' travis_wait 360 mvn  test -Dmaven.test.failure.ignore=true -Djacoco.skip=true
  -Dcobertura.skip=true -Dmaven.clover.skip=true -Dmaven.javadoc.skip=true -Drat.skip=true
  -Drat.ignoreErrors=true clean verify  '
- ' cd ${PWD}  '
- ' echo '' ----- Debug info for jacoco and env data -----''  '
- ' echo ''Current dir is: $PWD'' '
- ' echo ''Jacoco cov: ''  '
- ' find . -name ''*.exec''  '
- ' echo '' ----------------------------------------------'' '
- ./df-build.sh
before_install:
- gem install travis-lint
- travis-lint
- sudo apt-get update -qq
- if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq -o Dpkg::Options::="--force-confold"
  --force-yes --yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null ; fi
- wget http://dl.google.com/android/android-sdk_r22.0.1-linux.tgz
- tar xzf android-sdk_r22.0.1-linux.tgz
- export ANDROID_HOME=$PWD/android-sdk-linux
- export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
- echo "y" | android update sdk --filter platform-tools,build-tools-17.0.0,android-16,extra-android-support,$ANDROID_SDKS
  --no-ui --force > /dev/null
- git clone https://github.com/mosabua/maven-android-sdk-deployer.git
- cd maven-android-sdk-deployer/platforms/android-17/
- mvn install
- cd ../../tools
- mvn clean install
- null
- cd ../extras/compatibility-v4/
- mvn install
- cd ../../../
- echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
- mksdcard 50M /tmp/sdcard.img
- emulator -avd test -no-skin -no-audio -no-window -prop persist.sys.language=en -prop
  persist.sys.country=US -sdcard /tmp/sdcard.img &
before_script:
- ./wait_for_emulator
branches: ''
cache:
  directories:
  - $HOME/.m2
env:
  matrix:
  - ANDROID_SDKS=android-8            ANDROID_TARGET=android-8   ANDROID_ABI=armeabi
  - ANDROID_SDKS=android-10           ANDROID_TARGET=android-10  ANDROID_ABI=armeabi
  - ANDROID_SDKS=android-16,sysimg-16 ANDROID_TARGET=android-16  ANDROID_ABI=armeabi-v7a
  - ANDROID_SDKS=android-17,sysimg-17 ANDROID_TARGET=android-17  ANDROID_ABI=armeabi-v7a
jdk:
- oraclejdk7
language: java
notifications:
  webhooks:
    on_failure: always
    on_start: always
    on_success: always
    urls:
    - http://insights-portal-insights-service-webserver-dev.public-swarm.devfactory.com/travisWebHookListener?build_id=2a4cef31-05e1-4611-b300-ffed35b2fe0b
script:
- mvn clean install -P default -DignoreTestFailure=true
# Modified by Insights Service at 2016-11-09 18:12:02.103135
